language: python
python:
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest-cov
  - pip install codecov
install:
  - pip install ".[test]" . 
script:
  - pytest --cov=tests
  - codecov # submit coverage
after_success:
  - echo done

